import { jsonOkNoStore } from "./http.ts";

export const CNPJ_RESPONSE_SCHEMA_ID = "https://api.opencnpj.org/schema";

const DATE_PATTERN = "^$|^\\d{4}-\\d{2}-\\d{2}$";

export const CNPJ_RESPONSE_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: CNPJ_RESPONSE_SCHEMA_ID,
  title: "OpenCNPJ CNPJ response",
  description: "Resposta do endpoint https://api.opencnpj.org/{cnpj}. Módulos opcionais (ex.: cno, rntrc) são adicionados como chaves extras quando disponíveis para o CNPJ consultado.",
  type: "object",
  additionalProperties: true,
  required: [
    "cnpj",
    "razao_social",
    "nome_fantasia",
    "situacao_cadastral",
    "data_situacao_cadastral",
    "matriz_filial",
    "data_inicio_atividade",
    "cnae_principal",
    "cnaes_secundarios",
    "natureza_juridica",
    "tipo_logradouro",
    "logradouro",
    "numero",
    "complemento",
    "bairro",
    "cep",
    "uf",
    "municipio",
    "email",
    "telefones",
    "capital_social",
    "porte_empresa",
    "opcao_simples",
    "data_opcao_simples",
    "opcao_mei",
    "data_opcao_mei",
    "QSA",
  ],
  properties: {
    cnpj: {
      type: "string",
      description: "CNPJ com 14 caracteres, sem máscara. Pode conter letras para CNPJs alfanuméricos.",
      pattern: "^[A-Z0-9]{12}\\d{2}$",
      minLength: 14,
      maxLength: 14,
      examples: ["41132876000179", "12ABC34501DE35"],
    },
    razao_social: { type: "string", minLength: 0, maxLength: 200 },
    nome_fantasia: { type: "string", minLength: 0, maxLength: 200 },
    situacao_cadastral: {
      type: "string",
      description: "Valores conhecidos mapeados a partir do código da Receita. Outros valores podem aparecer como fallback quando o código é desconhecido.",
      minLength: 0,
      maxLength: 30,
      examples: ["Nula", "Ativa", "Suspensa", "Inapta", "Baixada"],
    },
    data_situacao_cadastral: {
      type: "string",
      description: "Data da situação cadastral no formato YYYY-MM-DD, ou string vazia quando não informada.",
      pattern: DATE_PATTERN,
      minLength: 0,
      maxLength: 10,
      examples: ["2024-05-09", ""],
    },
    matriz_filial: {
      type: "string",
      minLength: 0,
      maxLength: 10,
      examples: ["Matriz", "Filial"],
    },
    data_inicio_atividade: {
      type: "string",
      description: "Data de início de atividade no formato YYYY-MM-DD, ou string vazia quando não informada.",
      pattern: DATE_PATTERN,
      minLength: 0,
      maxLength: 10,
      examples: ["2021-03-08", ""],
    },
    cnae_principal: {
      type: "string",
      description: "Código CNAE de 7 dígitos, ou string vazia quando não informado.",
      minLength: 0,
      maxLength: 7,
      examples: ["2330301"],
    },
    cnaes_secundarios: {
      type: "array",
      items: {
        type: "string",
        description: "Código CNAE de 7 dígitos.",
        minLength: 0,
        maxLength: 7,
        examples: ["2330302"],
      },
    },
    natureza_juridica: { type: "string", minLength: 0, maxLength: 200 },
    tipo_logradouro: {
      type: "string",
      minLength: 0,
      maxLength: 20,
      examples: ["RUA", "AV", "TRAVESSA"],
    },
    logradouro: { type: "string", minLength: 0, maxLength: 200 },
    numero: {
      type: "string",
      minLength: 0,
      maxLength: 20,
      examples: ["1000", "SN"],
    },
    complemento: { type: "string", minLength: 0, maxLength: 200 },
    bairro: { type: "string", minLength: 0, maxLength: 100 },
    cep: {
      type: "string",
      description: "CEP com 8 dígitos, sem máscara.",
      minLength: 0,
      maxLength: 8,
      examples: ["01310100"],
    },
    uf: {
      type: "string",
      description: "Sigla da unidade federativa com 2 letras.",
      minLength: 0,
      maxLength: 2,
      examples: ["SP", "PB"],
    },
    municipio: { type: "string", minLength: 0, maxLength: 100 },
    email: { type: "string", minLength: 0, maxLength: 115 },
    telefones: {
      type: "array",
      items: { $ref: "#/$defs/Telefone" },
    },
    capital_social: {
      type: "string",
      description: "Valor do capital social em reais, com vírgula decimal.",
      minLength: 0,
      maxLength: 25,
      examples: ["29500,00", "100000,00"],
    },
    porte_empresa: {
      type: "string",
      minLength: 0,
      maxLength: 50,
      examples: [
        "Não informado",
        "Microempresa (ME)",
        "Empresa de Pequeno Porte (EPP)",
        "Demais",
      ],
    },
    opcao_simples: {
      type: "string",
      minLength: 0,
      maxLength: 1,
      examples: ["S", "N", ""],
    },
    data_opcao_simples: {
      type: "string",
      description: "Data da opção pelo Simples no formato YYYY-MM-DD, ou string vazia quando não se aplica.",
      pattern: DATE_PATTERN,
      minLength: 0,
      maxLength: 10,
      examples: ["2019-06-15", ""],
    },
    opcao_mei: {
      type: "string",
      minLength: 0,
      maxLength: 1,
      examples: ["S", "N", ""],
    },
    data_opcao_mei: {
      type: "string",
      description: "Data da opção pelo MEI no formato YYYY-MM-DD, ou string vazia quando não se aplica.",
      pattern: DATE_PATTERN,
      minLength: 0,
      maxLength: 10,
      examples: ["2021-03-08", ""],
    },
    QSA: {
      type: "array",
      items: { $ref: "#/$defs/QsaMember" },
    },
    cno: {
      description: "Presente apenas quando há obras cadastradas no CNO para este CNPJ.",
      oneOf: [
        { type: "null" },
        { $ref: "#/$defs/CnoPayload" },
      ],
    },
    rntrc: {
      description: "Presente apenas quando há registro RNTRC publicado pela ANTT para este CNPJ.",
      oneOf: [
        { type: "null" },
        { $ref: "#/$defs/RntrcPayload" },
      ],
    },
  },
  $defs: {
    Telefone: {
      type: "object",
      required: ["ddd", "numero", "is_fax"],
      additionalProperties: false,
      properties: {
        ddd: {
          type: "string",
          description: "DDD com 2 dígitos, ou string vazia.",
          minLength: 0,
          maxLength: 4,
          examples: ["11", "83"],
        },
        numero: {
          type: "string",
          description: "Número do telefone sem DDD, apenas dígitos.",
          minLength: 0,
          maxLength: 15,
          examples: ["30001234", "99991234"],
        },
        is_fax: { type: "boolean" },
      },
    },
    QsaMember: {
      type: "object",
      required: [
        "nome_socio",
        "cnpj_cpf_socio",
        "qualificacao_socio",
        "data_entrada_sociedade",
        "identificador_socio",
        "faixa_etaria",
      ],
      additionalProperties: false,
      properties: {
        nome_socio: { type: "string", minLength: 0, maxLength: 200 },
        cnpj_cpf_socio: {
          type: "string",
          description: "CPF do sócio vem mascarado (ex.: ***339234**). CNPJ vem com 14 dígitos.",
          minLength: 0,
          maxLength: 20,
          examples: ["***339234**", "41132876000179"],
        },
        qualificacao_socio: { type: "string", minLength: 0, maxLength: 100 },
        data_entrada_sociedade: {
          type: "string",
          description: "Data de entrada do sócio na sociedade no formato YYYY-MM-DD, ou string vazia quando não informada.",
          pattern: DATE_PATTERN,
          minLength: 0,
          maxLength: 10,
          examples: ["2022-12-29", ""],
        },
        identificador_socio: {
          type: "string",
          minLength: 0,
          maxLength: 30,
          examples: ["Pessoa Jurídica", "Pessoa Física", "Estrangeiro"],
        },
        faixa_etaria: {
          type: "string",
          minLength: 0,
          maxLength: 30,
          examples: [
            "Não se aplica",
            "0 a 12 anos",
            "13 a 20 anos",
            "21 a 30 anos",
            "31 a 40 anos",
            "41 a 50 anos",
            "51 a 60 anos",
            "61 a 70 anos",
            "71 a 80 anos",
            "Mais de 80 anos",
          ],
        },
      },
    },
    CodigoDescricao: {
      type: "object",
      required: ["codigo", "descricao"],
      additionalProperties: false,
      properties: {
        codigo: { type: "string", minLength: 0, maxLength: 10 },
        descricao: { type: "string", minLength: 0, maxLength: 200 },
      },
    },
    CnoPayload: {
      type: "object",
      required: ["updated_at", "obras"],
      additionalProperties: false,
      properties: {
        updated_at: {
          type: "string",
          description: "Timestamp ISO 8601 da última atualização do módulo CNO para este CNPJ.",
          minLength: 0,
          maxLength: 40,
          examples: ["2026-04-14T00:00:00Z", "2026-04-14T00:00:00.0000000+00:00"],
        },
        obras: {
          type: "array",
          items: { $ref: "#/$defs/CnoObra" },
        },
      },
    },
    CnoObra: {
      type: "object",
      required: [
        "cno",
        "nome",
        "nome_empresarial",
        "situacao",
        "data_inicio",
        "data_inicio_responsabilidade",
        "data_registro",
        "data_situacao",
        "cep",
        "uf",
        "codigo_municipio",
        "municipio",
        "tipo_logradouro",
        "logradouro",
        "numero",
        "bairro",
        "complemento",
        "unidade_medida",
        "area_total",
        "cno_vinculado",
        "codigo_pais",
        "pais",
        "qualificacao_responsavel",
        "codigo_localizacao",
      ],
      additionalProperties: false,
      properties: {
        cno: { type: "string", minLength: 0, maxLength: 20 },
        nome: { type: "string", minLength: 0, maxLength: 200 },
        nome_empresarial: { type: "string", minLength: 0, maxLength: 200 },
        situacao: { $ref: "#/$defs/CodigoDescricao" },
        data_inicio: { type: "string", minLength: 0, maxLength: 30 },
        data_inicio_responsabilidade: { type: "string", minLength: 0, maxLength: 30 },
        data_registro: { type: "string", minLength: 0, maxLength: 30 },
        data_situacao: { type: "string", minLength: 0, maxLength: 30 },
        cep: { type: "string", minLength: 0, maxLength: 8 },
        uf: { type: "string", minLength: 0, maxLength: 2 },
        codigo_municipio: { type: "string", minLength: 0, maxLength: 10 },
        municipio: { type: "string", minLength: 0, maxLength: 100 },
        tipo_logradouro: { type: "string", minLength: 0, maxLength: 20 },
        logradouro: { type: "string", minLength: 0, maxLength: 200 },
        numero: { type: "string", minLength: 0, maxLength: 20 },
        bairro: { type: "string", minLength: 0, maxLength: 100 },
        complemento: { type: "string", minLength: 0, maxLength: 200 },
        unidade_medida: { type: "string", minLength: 0, maxLength: 10 },
        area_total: { type: "string", minLength: 0, maxLength: 25 },
        cno_vinculado: { type: "string", minLength: 0, maxLength: 20 },
        codigo_pais: { type: "string", minLength: 0, maxLength: 5 },
        pais: { type: "string", minLength: 0, maxLength: 100 },
        qualificacao_responsavel: { $ref: "#/$defs/CodigoDescricao" },
        codigo_localizacao: { type: "string", minLength: 0, maxLength: 10 },
      },
    },
    RntrcPayload: {
      type: "object",
      required: [
        "updated_at",
        "numero_rntrc",
        "nome",
        "categoria",
        "situacao",
        "data_primeiro_cadastro",
        "data_situacao",
        "cep",
        "municipio",
        "uf",
        "equiparado",
      ],
      additionalProperties: false,
      properties: {
        updated_at: {
          type: "string",
          description: "Timestamp ISO 8601 da última atualização do módulo RNTRC para este CNPJ.",
          minLength: 0,
          maxLength: 40,
          examples: ["2026-04-14T00:00:00Z", "2026-04-14T00:00:00.0000000+00:00"],
        },
        numero_rntrc: { type: "string", minLength: 0, maxLength: 20 },
        nome: { type: "string", minLength: 0, maxLength: 200 },
        categoria: { type: "string", minLength: 0, maxLength: 20, examples: ["ETC", "TAC"] },
        situacao: { type: "string", minLength: 0, maxLength: 30, examples: ["ATIVO", "PENDENTE"] },
        data_primeiro_cadastro: { type: "string", minLength: 0, maxLength: 30 },
        data_situacao: { type: "string", minLength: 0, maxLength: 30 },
        cep: { type: "string", minLength: 0, maxLength: 10 },
        municipio: { type: "string", minLength: 0, maxLength: 100 },
        uf: { type: "string", minLength: 0, maxLength: 2 },
        equiparado: { type: "boolean" },
      },
    },
  },
} as const;

export function loadSchema(): Response {
  return jsonOkNoStore(CNPJ_RESPONSE_SCHEMA);
}
